'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/stores/authStore';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { CheckCircle, Users, Zap, GitBranch } from 'lucide-react';

/**
 * TaskFlow Landing Page
 *
 * Marketing page for TaskFlow application.
 * Generated based on PROJECT_BRIEF.md requirements.
 */

export default function LandingPage() {
  const router = useRouter();
  const { user, isLoading } = useAuthStore();

  useEffect(() => {
    // Redirect authenticated users to dashboard
    if (user && !isLoading) {
      router.push('/dashboard');
    }
  }, [user, isLoading, router]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Hero Section */}
      <header className="container mx-auto px-4 py-16">
        <nav className="flex justify-between items-center mb-16">
          <div className="flex items-center space-x-2">
            <CheckCircle className="h-8 w-8 text-blue-600" />
            <span className="text-2xl font-bold text-gray-900">TaskFlow</span>
          </div>
          <div className="space-x-4">
            <Button variant="ghost" onClick={() => router.push('/login')}>
              Log In
            </Button>
            <Button onClick={() => router.push('/signup')}>
              Get Started
            </Button>
          </div>
        </nav>

        <div className="text-center max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Manage Tasks with Your Team in Real-Time
          </h1>
          <p className="text-xl text-gray-600 mb-8">
            TaskFlow helps teams organize work, track progress, and collaborate
            seamlessly. Built for modern development teams.
          </p>
          <div className="flex gap-4 justify-center">
            <Button size="lg" onClick={() => router.push('/signup')}>
              Start Free Trial
            </Button>
            <Button size="lg" variant="outline" onClick={() => router.push('/demo')}>
              Watch Demo
            </Button>
          </div>
        </div>
      </header>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-16">
        <h2 className="text-3xl font-bold text-center mb-12">
          Everything Your Team Needs
        </h2>
        <div className="grid md:grid-cols-3 gap-8">
          <Card className="p-6">
            <Zap className="h-12 w-12 text-blue-600 mb-4" />
            <h3 className="text-xl font-semibold mb-2">Real-Time Collaboration</h3>
            <p className="text-gray-600">
              See updates instantly as your team works. No refresh needed.
            </p>
          </Card>

          <Card className="p-6">
            <Users className="h-12 w-12 text-blue-600 mb-4" />
            <h3 className="text-xl font-semibold mb-2">Team Management</h3>
            <p className="text-gray-600">
              Organize your team with roles, permissions, and projects.
            </p>
          </Card>

          <Card className="p-6">
            <GitBranch className="h-12 w-12 text-blue-600 mb-4" />
            <h3 className="text-xl font-semibold mb-2">GitHub Integration</h3>
            <p className="text-gray-600">
              Link tasks to issues and PRs. Perfect for dev teams.
            </p>
          </Card>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-4 py-16 text-center">
        <div className="max-w-2xl mx-auto bg-blue-600 rounded-2xl p-12 text-white">
          <h2 className="text-3xl font-bold mb-4">
            Ready to Transform Your Workflow?
          </h2>
          <p className="text-xl mb-8 opacity-90">
            Join thousands of teams using TaskFlow to ship faster.
          </p>
          <Button size="lg" variant="secondary">
            Start Free Trial
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="container mx-auto px-4 py-8 text-center text-gray-600">
        <p>Generated by AI using ai-project-template</p>
      </footer>
    </div>
  );
}
