import request from 'supertest';
import { app } from '../../src/backend/server';
import { prisma } from '../../src/backend/config/database';
import { generateAuthToken } from '../../src/backend/utils/auth';

/**
 * Task API Tests
 *
 * Comprehensive test suite for task management endpoints.
 * Generated by AI based on PROJECT_BRIEF.md requirements.
 *
 * Tests cover:
 * - Task CRUD operations
 * - Authorization checks
 * - Input validation
 * - Edge cases
 */

describe('Task API', () => {
  let authToken: string;
  let userId: string;
  let projectId: string;
  let taskId: string;

  beforeAll(async () => {
    // Create test user and project
    const user = await prisma.user.create({
      data: {
        email: 'test@taskflow.com',
        name: 'Test User',
        password: 'hashed_password',
      },
    });
    userId = user.id;
    authToken = generateAuthToken(user);

    const team = await prisma.team.create({
      data: {
        name: 'Test Team',
        slug: 'test-team',
        ownerId: userId,
      },
    });

    const project = await prisma.project.create({
      data: {
        name: 'Test Project',
        teamId: team.id,
      },
    });
    projectId = project.id;
  });

  afterAll(async () => {
    // Clean up test data
    await prisma.task.deleteMany({});
    await prisma.project.deleteMany({});
    await prisma.team.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.$disconnect();
  });

  describe('POST /api/v1/tasks', () => {
    it('should create a new task with valid data', async () => {
      const taskData = {
        title: 'Implement user authentication',
        description: 'Add JWT-based authentication',
        priority: 'HIGH',
        status: 'TODO',
        projectId,
      };

      const response = await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send(taskData)
        .expect(201);

      expect(response.body).toMatchObject({
        title: taskData.title,
        description: taskData.description,
        priority: taskData.priority,
        status: taskData.status,
        projectId: taskData.projectId,
        creatorId: userId,
      });

      taskId = response.body.id;
    });

    it('should return 400 for invalid task data', async () => {
      const invalidData = {
        title: '', // Empty title
        projectId,
      };

      await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send(invalidData)
        .expect(400);
    });

    it('should return 401 without authentication', async () => {
      const taskData = {
        title: 'Test task',
        projectId,
      };

      await request(app)
        .post('/api/v1/tasks')
        .send(taskData)
        .expect(401);
    });
  });

  describe('GET /api/v1/tasks/:id', () => {
    it('should retrieve task by ID', async () => {
      const response = await request(app)
        .get(`/api/v1/tasks/${taskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(response.body).toMatchObject({
        id: taskId,
        title: 'Implement user authentication',
      });
    });

    it('should return 404 for non-existent task', async () => {
      const fakeId = '00000000-0000-0000-0000-000000000000';

      await request(app)
        .get(`/api/v1/tasks/${fakeId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(404);
    });
  });

  describe('PATCH /api/v1/tasks/:id', () => {
    it('should update task status', async () => {
      const updateData = {
        status: 'IN_PROGRESS',
      };

      const response = await request(app)
        .patch(`/api/v1/tasks/${taskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .send(updateData)
        .expect(200);

      expect(response.body.status).toBe('IN_PROGRESS');
    });

    it('should update task assignee', async () => {
      const updateData = {
        assigneeId: userId,
      };

      const response = await request(app)
        .patch(`/api/v1/tasks/${taskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .send(updateData)
        .expect(200);

      expect(response.body.assigneeId).toBe(userId);
    });
  });

  describe('GET /api/v1/projects/:projectId/tasks', () => {
    it('should list all tasks for a project', async () => {
      const response = await request(app)
        .get(`/api/v1/projects/${projectId}/tasks`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      expect(Array.isArray(response.body)).toBe(true);
      expect(response.body.length).toBeGreaterThan(0);
    });

    it('should filter tasks by status', async () => {
      const response = await request(app)
        .get(`/api/v1/projects/${projectId}/tasks?status=IN_PROGRESS`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      response.body.forEach((task: any) => {
        expect(task.status).toBe('IN_PROGRESS');
      });
    });

    it('should filter tasks by priority', async () => {
      const response = await request(app)
        .get(`/api/v1/projects/${projectId}/tasks?priority=HIGH`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(200);

      response.body.forEach((task: any) => {
        expect(task.priority).toBe('HIGH');
      });
    });
  });

  describe('DELETE /api/v1/tasks/:id', () => {
    it('should delete a task', async () => {
      await request(app)
        .delete(`/api/v1/tasks/${taskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(204);

      // Verify task is deleted
      await request(app)
        .get(`/api/v1/tasks/${taskId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .expect(404);
    });
  });

  describe('Edge Cases', () => {
    it('should handle concurrent task updates', async () => {
      // Create a new task
      const task = await prisma.task.create({
        data: {
          title: 'Concurrent test',
          projectId,
          creatorId: userId,
        },
      });

      // Simulate concurrent updates
      const updates = [
        request(app)
          .patch(`/api/v1/tasks/${task.id}`)
          .set('Authorization', `Bearer ${authToken}`)
          .send({ status: 'IN_PROGRESS' }),
        request(app)
          .patch(`/api/v1/tasks/${task.id}`)
          .set('Authorization', `Bearer ${authToken}`)
          .send({ priority: 'HIGH' }),
      ];

      const responses = await Promise.all(updates);

      responses.forEach(response => {
        expect([200, 409]).toContain(response.status);
      });
    });

    it('should validate due date is in the future', async () => {
      const pastDate = new Date('2020-01-01');

      const response = await request(app)
        .post('/api/v1/tasks')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          title: 'Past due task',
          projectId,
          dueDate: pastDate,
        })
        .expect(400);

      expect(response.body.error).toContain('due date');
    });
  });
});
