import express, { Application } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import { createServer } from 'http';
import { Server } from 'socket.io';
import { config } from './config';
import { errorHandler } from './middleware/errorHandler';
import { requestLogger } from './middleware/requestLogger';
import { rateLimiter } from './middleware/rateLimiter';
import authRoutes from './routes/auth.routes';
import taskRoutes from './routes/task.routes';
import projectRoutes from './routes/project.routes';
import teamRoutes from './routes/team.routes';
import { setupSocketHandlers } from './sockets';
import { logger } from './utils/logger';

/**
 * TaskFlow Backend Server
 *
 * This is the main entry point for the TaskFlow API server.
 * It sets up Express, Socket.io for real-time features, and all routes.
 *
 * Generated by AI from PROJECT_BRIEF.md requirements.
 */

class TaskFlowServer {
  public app: Application;
  private httpServer;
  private io: Server;

  constructor() {
    this.app = express();
    this.httpServer = createServer(this.app);
    this.io = new Server(this.httpServer, {
      cors: {
        origin: config.frontendUrl,
        credentials: true,
      },
    });

    this.initializeMiddlewares();
    this.initializeRoutes();
    this.initializeSockets();
    this.initializeErrorHandling();
  }

  private initializeMiddlewares(): void {
    // Security middleware
    this.app.use(helmet());
    this.app.use(cors({
      origin: config.frontendUrl,
      credentials: true,
    }));

    // Performance middleware
    this.app.use(compression());

    // Request parsing
    this.app.use(express.json());
    this.app.use(express.urlencoded({ extended: true }));

    // Logging and rate limiting
    this.app.use(requestLogger);
    this.app.use(rateLimiter);
  }

  private initializeRoutes(): void {
    // Health check
    this.app.get('/health', (req, res) => {
      res.json({ status: 'ok', timestamp: new Date().toISOString() });
    });

    // API routes
    this.app.use('/api/v1/auth', authRoutes);
    this.app.use('/api/v1/tasks', taskRoutes);
    this.app.use('/api/v1/projects', projectRoutes);
    this.app.use('/api/v1/teams', teamRoutes);
  }

  private initializeSockets(): void {
    setupSocketHandlers(this.io);
  }

  private initializeErrorHandling(): void {
    this.app.use(errorHandler);
  }

  public start(): void {
    this.httpServer.listen(config.port, () => {
      logger.info(`TaskFlow server running on port ${config.port}`);
      logger.info(`Environment: ${config.nodeEnv}`);
    });
  }
}

// Start the server
const server = new TaskFlowServer();
server.start();

export default server;
